### ISSUE TITLE
Add other cool items guide

### ISSUE THREAD

**Issue by alisinabh** [zagortenay333/new-minty#11]
Hi :)

Thank you very much for your wonderful theme. :+1: 

The photo you've posted of theme on github page of project is awesome.
Can you please share the Control-theme, Icon-theme, Applets and even the background info?

I would really like to replicate what you've done there. It's awesome and minty :green_heart: 

Thank you!

**Comment by zagortenay333** [comment]
I did add the wallpaper and icons info; it's at the bottom of the screenshot. Not sure what you mean by control theme?
The applets are gpaste, and desktop screenshot.
The desklests are sticky-notes and reddit-reader.
The extension is gtile.

**Comment by alisinabh** [comment]
I'm sorry it was too small for me to see :D
Thank you very much

I'm a noob on arch with cinnamon. By control theme i mean them of window controls such as close, minimize and maximize.

**Comment by zagortenay333** [comment]
There are no gtk windows shown in that screenshot. That's all cinnamon.
